version: "3.9"

services:
  pgadmin:
    image: "dpage/pgadmin4:6.18"
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "Secure"
    ports:
      - "8080:80"
    restart: unless-stopped
    mem_limit: 500M
    healthcheck:
      # Check if pgadmin server is healthy by calling wget.
      # exit normalizes the exit code
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit 1
      interval: 2m
      timeout: 6s
      retries: 3
      start_period: 30s